### ISSUE TITLE
CampJS VI Budget

### ISSUE THREAD

**Issue by DamonOehlman** [campjs/campjs-vi#7]
As per my last comment in #6 I'm very keen for us to establish some kind of budget for this next camp.  I know Tim has been out of pocket for quite a few of the camps (I think we did manage to break even for the last camp).

Once we have some budget in place we can work backwards and do a best guestimate on ticket prices, etc.  If possible I'd like to take some pressure off the sponsorship team as I know that it can be difficult to raise the required sponsorship dollars and I think we were quite lucky to break even last time.

So on that note, let's start listing out expenses for the event and rough costings for them (rounded up ideally).  I reckon we can pretty much bet on having 100 people at minimum so that makes sense to be the number we use to roughly calculate the break even ticket cost.

So, expenses... go:

**Comment by SomeoneWeird** [comment]
Would be very useful to know what the prices are per person for the actual venue.

Some thoughts off the top of my head:
- Drinks (alcohol/softdrink/juice/whatever)
- Flights for international speakers (no idea if we've paid for ones previously)
- Projectors
- Speaker Equipment

**Comment by weilu** [comment]
This is what we have last time:

## Attendance Dependent Costs

Accommodation
Lanyard
T-Shirt

## Fixed Costs

Bus (2 x 48 seat)
Tables
Food
Coffee
Fridges
Outdoor Table Umbrellas
Alcohol
Network Gear
Projectors
Video
Design
Stickers
Speaker Travel
Sound Systems

**Comment by MauriceButler** [comment]
These lists are a great start, are we able to work back from ticket sales for last camp to how much each of these cost per person?

If not itemised at least a per person amount of $ we should target?

I assume $ values are not a secret and can be worked on here as this whole thing is open and not for profit anyway?

**Comment by DamonOehlman** [comment]
I know @weilu reconciled $$$ after the last camp, but as I mentioned earlier Tim has always had a view that he would absorb some of the costs so I don't think its heavily itemized at this stage.  What I think we can do moving forward is set up a shared spreadsheet (I'm guessing Google Drive or something is going to be the best system unless someone has a better idea) with estimated costs and start to crunch the numbers for the next camp.  I'm happy to kick this off, if we are in general agreement that Alphabet Drive is the place to do this.

Additionally, one thing that isn't covered in the list above is the costs involved in bringing a few key speakers (usually international) out to the event.  Some super awesome folks pay their own way as they understand how cool it is to visit Australia, but we definitely cover flight costs for others to help things along.  I know Tim feels this is a strong differentiator about what makes CampJS what it is, and I agree with him.  I would like us to quantify that a bit this time around and have us all think about how much of a per/person ticket cost this is worth to the event.  For example, if through the open governance model we generally agree it's something like $50; and we have 100 people then that means we have $5K in our incentivising interesting people budget.  As for how that is spent I believe that is best left up to the which I think the speaker coordination group - see #1.

**Comment by DamonOehlman** [comment]
Also, thanks @weilu for getting that list there - that's fantastic :)

**Comment by SomeoneWeird** [comment]
@DamonOehlman to alphabet drive it is!

**Comment by SomeoneWeird** [comment]
Do we have any idea about what's going to happen with money? Who is going to be in charge of collecting it etc?

**Comment by DamonOehlman** [comment]
I'm hoping @timoxley and @weilu is still happy to be that conduit for this time around, which is why I'm very keen to make sure we cover costs.  Ideally if there is any money left in the kitty this time around we could use the funds to pay registration fees for whatever the thing is that is going to be the not-for-profit we starting talking about at the last camp.

**Comment by DamonOehlman** [comment]
With a wedding around the same time though, I completely understand if this is too much for them.  If that is the case, then I'll look at pushing forward with some kind of organisation registration prior to the next event... :fearful:

**Comment by DamonOehlman** [comment]
OK doc is here (anyone can comment):

https://docs.google.com/spreadsheets/d/1OxeFbpou22IrWcTS4ZMN--Wq8TywzPODVZkshfg4Dgs/edit?usp=sharing

Happy to provide people editing access that would like it also, just LMK.  If your email is public on you github profile then just let me know via a comment, otherwise email me (damon.oehlman@gmail.com).

**Comment by MauriceButler** [comment]
Do we need a tab / column for locked in sponsorships, ticket sales etc so we can see income vs expenditure?

**Comment by DamonOehlman** [comment]
OK, I've reworked the spreadsheet pretty significantly to try and help work out the optimal ticket price based on some estimated costs.  Currently, I'm working the figures based the budget on potentially a BYO conference as there is some inertia in that direction, but nothing is fixed in stone so please don't stress too much about it.

The layout now is 3 main tabs with a some additional utility tabs:
1. Costs - the stuff we absolutely need to make the event happen. Accommodation and Food costs have been provided by Koonjewarre.
2. Ticket Price - this is a bit of a matrix comparing ticket prices with estimated ticket sales, and how much will go into the "Nice Things" budget.  I feel comfortable that we should easily hit 80 registrations, but don't want to count any chickens before they are hatched.  At this baseline, I feel like we could probably achieve a BYO ticket price of $330 per person.
3. Nice Things - this is the list of "stretch goals" that we have for the event.  I've investigated costs of bringing a coffee cart out to the event with a trained barista and nothing is concrete, but I think those costs are indicative.  We should add other things here too.

Some additional things to note:
- I have allowed 4K for a Travel / Attendance Subsidy allowance in the must have costs.  I originally had this in the nice to haves but I think not allocating some budget to this in our baseline costs is not doing the right thing by the CampJS community.  I do feel that we should have more budget for this in our stretch goals also.
- There is no sponsorship figures included in the estimates.  This doesn't mean that we shouldn't attempt to get sponsors for CampJS, but all sponsorship $$$ should go our stretch goals rather than covering our costs I think.
- I feel quite strongly that for CampJS VI we should just do one ticket cost across the board, i.e. no SydJS, MelbJS, BrisJS discount codes. No early bird.  Just one ticket price.  This makes things simpler to manage and also financial transparency easier as well.

Thoughts are welcome - though I'll probably be asleep... so I'll get back to you all in the morning :)

**Comment by timoxley** [comment]
> I feel quite strongly that for CampJS VI we should just do one ticket cost across the board

Agreed! But people just don't buy tickets early unless there's some urgency, like a sale/discount ending – or the tickets are selling out. Human psychology. I would like to get the expert opinion of the mighty @eugeneware here.

**Comment by timoxley** [comment]
> I feel comfortable that we should easily hit 80 registrations

@DamonOehlman This may be a too conservative. I'd suggest ~100 registrations minimum, ~110-120 probably, 130-140 max. We've never had less than 100 registrations by the start of the event, but we almost always have less than 100 only two or three weeks leading up to the event, which is harrowing.

**Comment by timoxley** [comment]
@DamonOehlman

> I'm hoping @timoxley and @weilu is still happy to be that conduit for this time around,

Would love to but we can't do it this time around, unless it's an emergency

**Comment by DamonOehlman** [comment]
@timoxley Thanks for the responses.  Re finances, no worries at all.

**Comment by eugeneware** [comment]
It's true (re: different ticket pricing and running promotions). 

People don't buy unless there's some kind of deadline, and reason to make a decision today, rather than come back later. It sucks, and it can feel manipulative, but it's just how we're wired as human beings. That's why you see most of the successful conferences have early bird discounts, etc. Because it works. 

Left to their own devices people won't do anything, they're distracted and your tiny message that shows up in their inbox will be soon forgotten.

The two big factors that will help ticket sales are:
1. Scarcity (described above)
2. Frequency of communication. Just finding a legitimate way to put a lot of emails in their inbox - could be full of great content, updates on new speakers, sessions, etc. But a regular drip feed between now and the conference will help keep it front of mind. In marketing, this is called a "check move". Regardless of how good or bad your message is, frequency is one of the most critical factors.

Combine these two things, and you've got the basis for a good sales strategy.

If you had to choose one of the two things - scarcity all the way. Do one or two 5 days sales (perhaps one early - and one a month before the event), with 3+ emails during the sale period  and you'll move a bunch of tickets.

Conferences cost a lot of money, and it's a huge shame to see all this amazing energy and hard work go into it, only to lose a bunch of money.

One great way to do this is to have effective communication. Don't think of it as sales - but as effective communication. We know CampJS is a great product, we just have to communicate why, with sufficient frequency that they'll notice, and give them a reason to take action.

**Comment by DamonOehlman** [comment]
Thanks Eugene - what if we were to create 3 ticket releases.  Not time limited, but just quantity limited, e.g.:
- 40 x $320
- 40 x $350
- after that: $375

That puts us at an average ticket price of $335 for the first 80 tickets, and I think that feels pretty comfortable to me.

**Comment by eugeneware** [comment]
I've done quantity based stuff in the past as well, and it works IF they actually sell out. Selling 40 tickets in a short period of time is actually a pretty hard ask. So if doesn't sell out in a period of 1-2 weeks then it doesn't really help achieve the urgency to take action.

So, you need to know that you're going to sell out quickly.

I generally combine the two (quantity and time scarcity). So if you don't sell out, you always have the deadline to fall back on. There's nothing worse then saying - there's only 40 tickets - go get em, and then ... crickets ... and then follow up in a weeks time, and say, there's still 38 tickets left... take action soon or your miss out. Doesn't work well.

So, you could combine them: Ie. Release 40 tickets and have a deadline (1-2 weeks). If you sell out, great - tell them! Then they'll pay attention with the next ticket release. If you don't you close the offer on the deadline, then they'll pay attention with the next ticket release.

But, also, the more complex the offer is, the less response their is (ie. a confused mind says "no"). So you have to be careful.

In all honesty, I think just running a series of price reduce, time-based offers is easier to understand.

Also, There's not a lot of difference in the price between $320 and $375. Ideally, you want at LEAST a 30% discount for early birds (I typically launch products with a 50% discount). 

Particularly with events, it's important to bring the conference close to break-even, and get minimum numbers to make the conference viable, which is why they do it. Then anything beyond that is a bonus.

And there's nothing stopping you to run a time limited sale near the event if ticket sales are slow too. There's no guarantee that you're going to do it, so the initial offer still works (as long as you're true to your word and raise the price after the offer has expired).

Hope that makes sense. Just my $0.02.

My suggestion. Make the "retail" price around $500, and then do special offers around $300 initally, and then $400 later on.

**Comment by DamonOehlman** [comment]
Thanks again Eugene, definitely gives me some good food for thought.

**Comment by timoxley** [comment]
Suggest perhaps we could use math to increase the ticket by a little bit price every day. edit: ugh. actually not sure if that will work either. Dunno.

**Comment by DamonOehlman** [comment]
Yeah, I like that idea :)

**Comment by DamonOehlman** [comment]
Thanks for all the really great discussion in this thread.  I'm going to close it now to try and keep the issue list tight, but I imagine I'll be referring back to it soon in the future.

Also, tickets on sale - see #16 :)
