### ISSUE TITLE
Ticket Sales

### ISSUE THREAD

**Issue by MauriceButler** [campjs/campjs-vi#9]
So in #6 it was mentioned we used ti.to last time and it was great.

Do we have an existing account with ti.to ?

Personally I think we should get tickets sellable and the link on the website ASAP for a few reasons
1. We are getting really close to the date and need to start locking in people before other plans get made
2. Will assist with budgeting and ease some of the unknow around budget
3. I know of a number of people that will purchase a ticket straight away
4. Need to confirm if any tickets were presold at the end of last camp.

**Comment by DamonOehlman** [comment]
So yes, we have a ti.to account and it is excellent.

I don't agree that we need to get ticket sales up before we have a realistic baseline cost worked out for the event. Definitely agree that we need to confirm 4 but I'm not sure how getting ticket sales up will help sort this out.

I personally think some of the early, early, early bird low priced tickets have been a bit of a problem as they run at a significant loss and really don't want to fall into that trap again.  Both for Tim's sake and for all of ours.  If there are any tickets that run at a loss it should be to assist people who can't afford to get to the event otherwise, get to the event.

@timoxley Did you actually presell any tickets for this next camp?

**Comment by DamonOehlman** [comment]
To give some context, here is a screenshot of ticket sales data for CampJS V:

![campjs-ticket-sales-overtime](https://cloud.githubusercontent.com/assets/609693/9321128/a2643452-45a5-11e5-99d5-d30bd1046c57.png)

Initial run for early, early, early bird tickets.  And then the bulk of the sales in the month or two before the event...

**Comment by MauriceButler** [comment]
I agree the baseline / ticket cost needs to be confirmed before this is done but am also trying to use issue as a push for those tasks too :smirk:

Import actions for this issue right now is as above were there any presales.

**Comment by DamonOehlman** [comment]
> I agree the baseline / ticket cost needs to be confirmed before this is done but am also trying to use issue as a push for those tasks too :smirk:

Yeah, that's a good plan :)  Love your work.

**Comment by MauriceButler** [comment]
Very good that info is helpfull. 

Also proves though we need to get into gear as we are only ~3 months out.

**Comment by DamonOehlman** [comment]
True.  I've emailed Koonjewarre to try and get an understanding of the primary accommodation / food costs.

**Comment by DamonOehlman** [comment]
ti.to page setup, people are able to register their interest:

https://ti.to/campjs/campjs-vi

Once we have pricing close to sorted (and any financial things sorted - see #14), we'll start releasing the first batch of tickets (quantity TBD).

**Comment by timoxley** [comment]
This is where we ran a sale under the direction of @eugeneware:

![image](https://cloud.githubusercontent.com/assets/43438/9363184/7df8ceba-46d7-11e5-9347-e8b9a1e16dd5.png)

**Comment by timoxley** [comment]
>  Did you actually presell any tickets for this next camp?

Not this time.

**Comment by DamonOehlman** [comment]
Closed by #16
